---
title: "hamstr - modelling additional bioturbation error"
author: "Andrew M. Dolman"
date: "`r Sys.Date()`"
output:
  conflr::confluence_document:
    space_key: "EC"
    parent_id: 284328119
    toc: TRUE
    toc_depth: 4
    code_folding: hide
    supported_syntax_highlighting:
      r: r
      foo: bar
    update: true
    use_original_size: true
  pdf_document: 
    fig_crop: no
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE,
                      message = FALSE, warning = FALSE,
                      dpi = 92,
                      dev = "png",
                      dev.args = list(type = "cairo-png"))
```

```{r packages}
library(tidyverse)
library(hamstr)
library(replicatecoredata)
```

## With the boxcore data


Use subcore 1 which contains the small-n replicates

```{r}
### Test on boxcore data ---------
bc <- (replicatecoredata::OR1_1218.14C) %>%
  arrange(depth_cm)


bc %>%
  ggplot(aes(x = depth_cm, y = age.14C.cal, #colour = factor(tube),
             group = factor(tube),
             shape = factor(n.forams))) +
  geom_point() +
  #geom_line() +
  facet_wrap(~tube)

bc.sub <- bc %>%
  filter(tube == 1) %>%
  #filter(n.forams == 200) %>%
  arrange(depth_cm) %>%
  mutate(dpt = 1:n())#%>%

 #filter(n.forams == 200)
```


### First fit standard hamstr model

```{r}
ham.bc <- hamstr(bc.sub$depth_cm, obs_age = bc.sub$age.14C.cal, obs_err = bc.sub$age.14C.cal.se,
                 cores = 3)

plot(ham.bc)
```


### Now model additional uncertainty due to bioturbation.

Use a moderately informative prior on the bioturbation depth *L*

```{r}
ham.bt.bc <- hamstr(bc.sub$depth_cm, obs_age = bc.sub$age.14C.cal, obs_err = bc.sub$age.14C.cal.se,
                    n_ind = bc.sub$n.forams,
                    #n_ind = rep(1, nrow(bc.sub)),
                    model_bioturbation = TRUE,
                    inflate_errors = FALSE,
                    L_prior_mean = 10,
                    L_prior_shape = 2,
                 cores = 3)
```


```{r}
#shinystan::launch_shinystan(ham.bt.bc$fit)
post <- as.data.frame(ham.bt.bc$fit, pars = c("L", "bt_age")) %>%
  as_tibble() %>%
  dplyr::mutate(iter = 1:nrow(.)) %>%
  pivot_longer(cols = -iter) %>%
  mutate(dpt = readr::parse_number(name))
```


#### Prior and posterior of bioturbation depth

```{r}
prior <- tibble(
  x = seq(0, 50, 0.1),
  y = dgamma(x, ham.bt.bc$data$L_prior_shape,
             rate = ham.bt.bc$data$L_prior_shape/ham.bt.bc$data$L_prior_mean)
)

post %>%
  filter(name == "L[1]") %>%
  ggplot(aes(x = value, after_stat(density))) +
  geom_histogram(alpha = 0.5, aes(fill = "Posterior", colour = "Posterior")) +
  geom_line(data = prior, aes(x =x, y = y, colour = "Prior", fill = "Prior")) +
  theme_bw() +
  labs(subtitle = "Prior and posterior distribution of mixing depth, L")

rstan::summary(ham.bt.bc$fit, pars = "L")$summary
```


```{r}
tmp <- bc.sub %>%
  left_join(., filter(post, name != "L[1]"))
```


#### Comparison of the two models.

```{r, fig.height=8}
p1 <- plot(ham.bc, type = "age") +
  labs(subtitle = "") +
  expand_limits(y = c(0, 25000))
  
p2 <- plot(ham.bt.bc, type = "age") +
    geom_violin(data = tmp,
              aes(x = depth_cm, y = value, group = as.factor(dpt)),
              fill = "pink", colour = "pink", scale = "width",
              position = position_identity(), alpha = 0.25) +
  labs(subtitle = "Additional age uncertainty due to bioturbation")+
  expand_limits(y = c(0, 25000))

pj <- egg::ggarrange(p1, p2, draw = TRUE)
#plot(pj)
```

